version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "6379:6379"
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.git
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
