# Generated by Django 5.2.4 on 2025-07-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('max_tokens', models.IntegerField()),
                ('memory_usage', models.FloatField()),
                ('device', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LLMRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('duration', models.FloatField(null=True)),
                ('tokens_generated', models.IntegerField(default=0)),
                ('tokens_prompt', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
    ]
