# Generated by Django 5.2.4 on 2025-07-05 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='gpu_memory_utilization',
            field=models.FloatField(default=0.9),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='model_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='model_type',
            field=models.CharField(default='llama', max_length=50),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='tensor_parallel_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='vllm_port',
            field=models.IntegerField(default=8000),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='max_tokens',
            field=models.IntegerField(default=512),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='llm_dashboard.llmmodel'),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='temperature',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='top_p',
            field=models.FloatField(default=0.9),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='device',
            field=models.CharField(default='GPU', max_length=50),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='max_tokens',
            field=models.IntegerField(default=2048),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='memory_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='status',
            field=models.CharField(default='UNLOADED', max_length=20),
        ),
        migrations.AlterField(
            model_name='llmrequest',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
