# Generated by Django 5.2.4 on 2025-07-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_dashboard', '0002_llmmodel_gpu_memory_utilization_llmmodel_model_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='dtype',
            field=models.CharField(choices=[('auto', 'Auto'), ('float16', 'Float16'), ('bfloat16', 'BFloat16'), ('float32', 'Float32')], default='auto', max_length=20),
        ),
    ]
