# Generated by Django 5.2.4 on 2025-07-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_dashboard', '0003_llmmodel_dtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='loading_logs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='loading_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
