# Generated by Django 5.2.4 on 2025-07-09 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_dashboard', '0004_llmmodel_loading_logs_llmmodel_loading_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='embedding_model_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='max_context_tokens',
            field=models.IntegerField(default=4096),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='rag_strategy',
            field=models.CharField(choices=[('sliding_window', 'Sliding Window'), ('map_reduce', 'Map-Reduce'), ('hybrid', 'Hybrid')], default='sliding_window', max_length=20),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='reserve_tokens_for_response',
            field=models.IntegerField(default=512),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='supports_embeddings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='tokenizer_name',
            field=models.CharField(default='gpt-3.5-turbo', max_length=100),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='vector_store_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='vector_store_type',
            field=models.CharField(choices=[('faiss', 'FAISS'), ('chromadb', 'ChromaDB'), ('weaviate', 'Weaviate')], default='faiss', max_length=50),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='chunks_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='context_chunks_used',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='document_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='map_reduce_steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='rag_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='strategy_used',
            field=models.CharField(default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='total_context_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_indexed', models.BooleanField(default=False)),
                ('estimated_tokens', models.IntegerField(default=0)),
                ('chunk_strategy', models.CharField(choices=[('fixed_size', 'Fixed Size'), ('semantic', 'Semantic'), ('sliding', 'Sliding Window')], default='semantic', max_length=20)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='llm_dashboard.llmmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('vector_index', models.IntegerField()),
                ('embedding_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_count', models.IntegerField(default=0)),
                ('token_start_position', models.IntegerField(default=0)),
                ('token_end_position', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='llm_dashboard.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='llm_dashboa_documen_fd61cf_idx'), models.Index(fields=['vector_index'], name='llm_dashboa_vector__8e197f_idx')],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
