# Generated by Django 5.2.4 on 2025-07-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_dashboard', '0005_llmmodel_embedding_model_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='logs',
            field=models.TextField(blank=True),
        ),
    ]
