# Generated by Django 5.2.4 on 2025-07-15 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_dashboard', '0006_alter_llmrequest_options_llmrequest_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='llm_dashboard.llmmodel'),
        ),
    ]
